In [1]:
!pip install SPARQLWrapper
!pip install sparql-dataframe

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: SPARQLWrapper in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (2.0.0)
Requirement already satisfied: rdflib>=6.1.1 in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (from SPARQLWrapper) (7.5.0)
Requirement already satisfied: pyparsing<4,>=2.1.0 in c:\programdata\anaconda3\lib\site-packages (from rdflib>=6.1.1->SPARQLWrapper) (3.1.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sparql-dataframe in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (0.4)
Requirement already satisfied: pandas>=0.22.0 in c:\programdata\anaconda3\lib\site-packages (from sparql-dataframe) (2.2.2)
Requirement already satisfied: SPARQLWrapper>=1.8.1 in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (from sparql-dataframe) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->sparql-dataframe) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->sparql-dataframe) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->sparql-dataframe) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.22.0->sparql-dataframe) (2023.3)
Requirement already satisfied: rdflib>=6.1.1 in c:\users\niklasdörner\appdata\roaming\python\python312\site-packages (from SPARQLWrapper>=1.8.1->sparql-dataframe) (7.5.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.22.0->sparql-dataframe) (1.16.0)
Requirement already satisfied: pyparsing<4,>=2.1.0 in c:\programdata\anaconda3\lib\site-packages (from rdflib>=6.1.1->SPARQLWrapper>=1.8.1->sparql-dataframe) (3.1.2)

In [2]:
import sparql_dataframe

endpoint = "http://localhost:7200/repositories/mqtt4ssn"

In [3]:
NS = {
    "mqtt:": "https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#",
    "rdfs:": "http://www.w3.org/2000/01/rdf-schema#",
    "ex:": "http://example.org/",
    "sosa": "http://www.w3.org/ns/sosa/" 
}

In [4]:
import pandas as pd

def strip_namespaces(df, ns_map=NS):
    def shrink(val):
        if not isinstance(val, str):
            return val
        # ersetze bekannte Namespaces durch Prefix
        for pref, base in ns_map.items():
            if val.startswith(base):
                return pref + val[len(base):]
        # fallback: nur local name nach # oder /
        if "#" in val:
            return val.rsplit("#", 1)[-1]
        if "/" in val:
            return val.rsplit("/", 1)[-1]
        return val

    return df.map(shrink)

## Control Packet Hierachy

### CQ1.01u - Which MQTT Clients send which MQTT Control Packets?

In [5]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?client ?packet ?type WHERE {
  ?client a mqtt:Client ;
          mqtt:sendsControlPacket ?packet .

  ?packet a mqtt:ControlPacket ;
          a ?type .

  ?type rdfs:subClassOf* mqtt:ControlPacket .

  FILTER( STRSTARTS(STR(?type), STR(mqtt:)) )
  FILTER( ?type != mqtt:ControlPacket )
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

,client,packet,type
0,ex:Broker_emqx%40172.19.0.3,ex:PublishPacket_1764845861738,mqtt:PublishPacket
1,ex:Broker_emqx%40172.19.0.3,ex:AuthPacket_1764845861737,mqtt:AuthPacket
2,ex:Broker_emqx%40172.19.0.3,ex:PubcompPacket_1764845868422,mqtt:PubcompPacket
3,ex:Broker_emqx%40172.19.0.3,ex:PubackPacket_1764845868422,mqtt:PubackPacket
4,ex:Broker_emqx%40172.19.0.3,ex:PubrecPacket_1764845868422,mqtt:PubrecPacket
5,ex:Broker_emqx%40172.19.0.3,ex:PubrelPacket_1764845868422,mqtt:PubrelPacket
6,ex:Broker_emqx%40172.19.0.3,ex:AuthPacket_1764845868422,mqtt:AuthPacket
7,ex:Broker_emqx%40172.19.0.3,ex:PublishPacket_1764845868422,mqtt:PublishPacket
8,ex:Client_Client%201,ex:UnsubscribePacket_1764800251677,mqtt:UnsubscribePacket
9,ex:Client_Client%201,ex:PublishPacket_1764845861738,mqtt:PublishPacket
10,ex:Client_Client%201,ex:AuthPacket_1764845861737,mqtt:AuthPacket
11,ex:Client_Client%201,ex:PubcompPacket_1764845868422,mqtt:PubcompPacket
12,ex:Client_Client%201,ex:PubackPacket_1764845868422,mqtt:PubackPacket
13,ex:Client_Client%201,ex:PubrecPacket_1764845868422,mqtt:PubrecPacket
14,ex:Client_Client%201,ex:PubrelPacket_1764845868422,mqtt:PubrelPacket
15,ex:Client_Client%201,ex:AuthPacket_1764845868422,mqtt:AuthPacket
16,ex:Client_Client%201,ex:PublishPacket_1764845868422,mqtt:PublishPacket
17,ex:Client_Client%201,ex:AuthPacket_1764896932197,mqtt:AuthPacket

### CQ1.02u - Which MQTT Control Packets were sent (specializations)?

In [6]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?client ?packet ?type WHERE {
  ?client a mqtt:Client ;
          mqtt:sendsControlPacket ?packet .
  ?packet a mqtt:ControlPacket ;
          a ?type .

  ?type rdfs:subClassOf* mqtt:ControlPacket .

  FILTER( STRSTARTS(STR(?type), STR(mqtt:)) )
  FILTER( ?type != mqtt:ControlPacket )
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

,client,packet,type
0,ex:Broker_emqx%40172.19.0.3,ex:PublishPacket_1764845861738,mqtt:PublishPacket
1,ex:Broker_emqx%40172.19.0.3,ex:AuthPacket_1764845861737,mqtt:AuthPacket
2,ex:Broker_emqx%40172.19.0.3,ex:PubcompPacket_1764845868422,mqtt:PubcompPacket
3,ex:Broker_emqx%40172.19.0.3,ex:PubackPacket_1764845868422,mqtt:PubackPacket
4,ex:Broker_emqx%40172.19.0.3,ex:PubrecPacket_1764845868422,mqtt:PubrecPacket
5,ex:Broker_emqx%40172.19.0.3,ex:PubrelPacket_1764845868422,mqtt:PubrelPacket
6,ex:Broker_emqx%40172.19.0.3,ex:AuthPacket_1764845868422,mqtt:AuthPacket
7,ex:Broker_emqx%40172.19.0.3,ex:PublishPacket_1764845868422,mqtt:PublishPacket
8,ex:Client_Client%201,ex:UnsubscribePacket_1764800251677,mqtt:UnsubscribePacket
9,ex:Client_Client%201,ex:PublishPacket_1764845861738,mqtt:PublishPacket
10,ex:Client_Client%201,ex:AuthPacket_1764845861737,mqtt:AuthPacket
11,ex:Client_Client%201,ex:PubcompPacket_1764845868422,mqtt:PubcompPacket
12,ex:Client_Client%201,ex:PubackPacket_1764845868422,mqtt:PubackPacket
13,ex:Client_Client%201,ex:PubrecPacket_1764845868422,mqtt:PubrecPacket
14,ex:Client_Client%201,ex:PubrelPacket_1764845868422,mqtt:PubrelPacket
15,ex:Client_Client%201,ex:AuthPacket_1764845868422,mqtt:AuthPacket
16,ex:Client_Client%201,ex:PublishPacket_1764845868422,mqtt:PublishPacket
17,ex:Client_Client%201,ex:AuthPacket_1764896932197,mqtt:AuthPacket

### CQ1.03u - Which MQTT Brokers sends which MQTT Control Packets?

In [7]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?broker ?packet ?type WHERE {
  ?broker a mqtt:Broker ;
          mqtt:sendsControlPacket ?packet .
  ?packet a mqtt:ControlPacket ;
          a ?type .

  ?type rdfs:subClassOf* mqtt:ControlPacket .

  FILTER( STRSTARTS(STR(?type), STR(mqtt:)) )
  FILTER( ?type != mqtt:ControlPacket )
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

,broker,packet,type
0,ex:Broker_emqx%40172.19.0.3,ex:PublishPacket_1764845861738,mqtt:PublishPacket
1,ex:Broker_emqx%40172.19.0.3,ex:AuthPacket_1764845861737,mqtt:AuthPacket
2,ex:Broker_emqx%40172.19.0.3,ex:PubcompPacket_1764845868422,mqtt:PubcompPacket
3,ex:Broker_emqx%40172.19.0.3,ex:PubackPacket_1764845868422,mqtt:PubackPacket
4,ex:Broker_emqx%40172.19.0.3,ex:PubrecPacket_1764845868422,mqtt:PubrecPacket
5,ex:Broker_emqx%40172.19.0.3,ex:PubrelPacket_1764845868422,mqtt:PubrelPacket
6,ex:Broker_emqx%40172.19.0.3,ex:AuthPacket_1764845868422,mqtt:AuthPacket
7,ex:Broker_emqx%40172.19.0.3,ex:PublishPacket_1764845868422,mqtt:PublishPacket
8,ex:Broker_emqx%40172.19.0.5,ex:AuthPacket_1764896932197,mqtt:AuthPacket

### CQ1.04u - Which MQTT Control Packets were sent by which Client (inverse)?

In [8]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?client ?packet ?type WHERE {
  ?client a mqtt:Client ;
          mqtt:sendsControlPacket ?packet .
  ?packet a mqtt:ControlPacket ;
          a ?type .

  ?type rdfs:subClassOf* mqtt:ControlPacket .

  FILTER( STRSTARTS(STR(?type), STR(mqtt:)) )
  FILTER( ?type != mqtt:ControlPacket )
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

,client,packet,type
0,ex:Broker_emqx%40172.19.0.3,ex:PublishPacket_1764845861738,mqtt:PublishPacket
1,ex:Broker_emqx%40172.19.0.3,ex:AuthPacket_1764845861737,mqtt:AuthPacket
2,ex:Broker_emqx%40172.19.0.3,ex:PubcompPacket_1764845868422,mqtt:PubcompPacket
3,ex:Broker_emqx%40172.19.0.3,ex:PubackPacket_1764845868422,mqtt:PubackPacket
4,ex:Broker_emqx%40172.19.0.3,ex:PubrecPacket_1764845868422,mqtt:PubrecPacket
5,ex:Broker_emqx%40172.19.0.3,ex:PubrelPacket_1764845868422,mqtt:PubrelPacket
6,ex:Broker_emqx%40172.19.0.3,ex:AuthPacket_1764845868422,mqtt:AuthPacket
7,ex:Broker_emqx%40172.19.0.3,ex:PublishPacket_1764845868422,mqtt:PublishPacket
8,ex:Client_Client%201,ex:UnsubscribePacket_1764800251677,mqtt:UnsubscribePacket
9,ex:Client_Client%201,ex:PublishPacket_1764845861738,mqtt:PublishPacket
10,ex:Client_Client%201,ex:AuthPacket_1764845861737,mqtt:AuthPacket
11,ex:Client_Client%201,ex:PubcompPacket_1764845868422,mqtt:PubcompPacket
12,ex:Client_Client%201,ex:PubackPacket_1764845868422,mqtt:PubackPacket
13,ex:Client_Client%201,ex:PubrecPacket_1764845868422,mqtt:PubrecPacket
14,ex:Client_Client%201,ex:PubrelPacket_1764845868422,mqtt:PubrelPacket
15,ex:Client_Client%201,ex:AuthPacket_1764845868422,mqtt:AuthPacket
16,ex:Client_Client%201,ex:PublishPacket_1764845868422,mqtt:PublishPacket
17,ex:Client_Client%201,ex:AuthPacket_1764896932197,mqtt:AuthPacket

### CQ1.05u - Which MQTT Publish packets carry Observations for a specific SOSA FeatureOfInterest or Property?

In [9]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/> 

SELECT ?packet ?message ?observationCollection ?foi ?property WHERE {
  ?packet a mqtt:PublishPacket ;
          mqtt:hasPublishPayload ?payload .
  ?payload a mqtt:Payload ;
          mqtt:hasApplicationMessage ?message .
  ?message a mqtt:ApplicationMessage ;       
          mqtt:applicationMessageEncodesObservationCollection ?observationCollection .
  ?activity a mqtt:Activity .
  OPTIONAL { ?activity sosa:hasFeatureOfInterest ?foi }
  OPTIONAL { 
    ?observationCollection sosa:hasMember ?observation .
    ?observation a sosa:Observation ;
                 sosa:observedProperty ?property .
  }
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

,packet,message,observationCollection,foi,property
0,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F1_2025-12-0...,NaN,ex:Property_GripPoint_X
1,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F1_2025-12-0...,NaN,ex:Property_GripPoint_Y
2,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F1_2025-12-0...,NaN,ex:Property_GripPoint_Z
3,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F1_2025-12-0...,NaN,ex:Property_GripPoint_X
4,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F1_2025-12-0...,NaN,ex:Property_GripPoint_Y
...,...,...,...,...,...
103,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F3_2025-12-0...,ex:FeatureOfInterest_RFID_87A3F3,ex:Property_GripPoint_Y
104,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F3_2025-12-0...,ex:FeatureOfInterest_RFID_87A3F3,ex:Property_GripPoint_Z
105,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F3_2025-12-0...,NaN,ex:Property_GripPoint_X
106,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F3_2025-12-0...,NaN,ex:Property_GripPoint_Y
107,ex:PublishPacket_1764845861738,ex:ApplicationMessage_1764845861738,ex:ObservationCollection_RFID_87A3F3_2025-12-0...,NaN,ex:Property_GripPoint_Z

### CQ1.06u - Which MQTT SUBSCRIBE packets request QoS=2 and for which filters?

In [10]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?packet ?entry ?filter WHERE {
  ?packet a mqtt:SubscribePacket ;
          mqtt:hasSubscribePayload ?payload .
  ?payload mqtt:hasSubscriptions ?entry .
  ?entry a mqtt:SubscriptionEntry .
  OPTIONAL { ?entry mqtt:hasQoSLevel 2 }
  OPTIONAL { ?entry mqtt:hasTopicFilter ?filter }

}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

,packet,entry,filter
0,ex:SubscribePacket_1764800258251,ex:SubscriptionEntry_actuator,ex:Topic_actuator

### CQ1.07u - Which MQTT UNSUBSCRIBE packets remove all filters under a certain path (e.g. 'factory/centering/#')?

In [11]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?packet ?filter WHERE {
  ?packet a mqtt:UnsubscribePacket ;
          mqtt:hasUnsubscribePayload ?payload .
  ?payload mqtt:hasTopicFilter ?filter .
  FILTER(STRSTARTS(?filter, "factory/centering/"))
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

Empty DataFrame
Columns: [packet, filter]
Index: []

### CQ1.08u - Which MQTT Control Packet has which Fixed Header / Variable Header / Payload?

In [12]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?packet ?type ?fixed ?variable ?payload WHERE {
  ?packet a mqtt:ControlPacket ;
       a ?type.

  OPTIONAL { ?packet mqtt:hasFixedHeader ?fixed }
  OPTIONAL { ?packet mqtt:hasVariableHeader ?variable }
  OPTIONAL { ?packet mqtt:hasPayload ?payload }


  ?type rdfs:subClassOf* mqtt:ControlPacket .

  FILTER( STRSTARTS(STR(?type), STR(mqtt:)) )
  FILTER( ?type != mqtt:ControlPacket )
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

,packet,type,fixed,variable,payload
0,ex:UnsubscribePacket_1764800251677,mqtt:UnsubscribePacket,ex:UnsubscribeFixedHeader_1764800251677,ex:UnsubscribeVariableHeader_1764800251677,ex:UnsubscribePayload_1764800251677
1,ex:SubscribePacket_1764800258251,mqtt:SubackPacket,ex:SubscribeFixedHeader_1764800258251,ex:SubscribeVariableHeader_1764800258251,ex:SubscribePayload_1764800258251
2,ex:SubscribePacket_1764800258251,mqtt:SubscribePacket,ex:SubscribeFixedHeader_1764800258251,ex:SubscribeVariableHeader_1764800258251,ex:SubscribePayload_1764800258251
3,ex:PublishPacket_1764845861738,mqtt:PublishPacket,ex:PublishFixedHeader_1764845861738,ex:PublishVariableHeader_1764845861738,ex:PublishPayload_1764845861738
4,ex:AuthPacket_1764845861737,mqtt:AuthPacket,ex:AuthFixedHeader_1764845861737,ex:AuthVariableHeader_1764845861737,NaN
5,ex:PubcompPacket_1764845868422,mqtt:PubcompPacket,ex:PubcompFixedHeader_1764845868422,ex:PubcompVariableHeader_1764845868422,NaN
6,ex:PubackPacket_1764845868422,mqtt:PubackPacket,ex:PubackFixedHeader_1764845868422,ex:PubackVariableHeader_1764845868422,NaN
7,ex:PubrecPacket_1764845868422,mqtt:PubrecPacket,ex:PubrecFixedHeader_1764845868422,ex:PubrecVariableHeader_1764845868422,NaN
8,ex:PubrelPacket_1764845868422,mqtt:PubrelPacket,ex:PubrelFixedHeader_1764845868422,ex:PubrelVariableHeader_1764845868422,NaN
9,ex:AuthPacket_1764845868422,mqtt:AuthPacket,ex:AuthFixedHeader_1764845868422,ex:AuthVariableHeader_1764845868422,NaN
10,ex:PublishPacket_1764845868422,mqtt:PublishPacket,ex:PublishFixedHeader_1764845868422,ex:PublishVariableHeader_1764845868422,ex:PublishPayload_1764845868422
11,ex:AuthPacket_1764896932197,mqtt:AuthPacket,ex:AuthFixedHeader_1764896932197,ex:AuthVariableHeader_1764896932197,NaN

### CQ1.09u - Which MQTT PUBLISH packet has which MQTT Topic (name) in the Variable Header?

In [13]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?packet ?topic WHERE {
  ?packet a mqtt:PublishPacket ;
          mqtt:hasPublishVariableHeader ?variable .
  ?variable mqtt:hasTopicName ?topic .
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

                           packet              topic
0  ex:PublishPacket_1764845861738    ex:Topic_sensor
1  ex:PublishPacket_1764845868422  ex:Topic_actuator

### CQ1.10u - Which QoS levels are set (in PUBLISH Fixed Header or SubscriptionEntry)?

In [14]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?entity ?qos WHERE {
  { ?entity a mqtt:PublishFixedHeader ; 
        mqtt:hasQoSLevel ?qos . }
  UNION
  { ?entity a mqtt:SubscriptionEntry ; 
        mqtt:hasQoSLevel ?qos . }
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

                                entity  qos
0  ex:PublishFixedHeader_1764845861738    2
1  ex:PublishFixedHeader_1764845868422    2
2  ex:PublishFixedHeader_1764845861738    2
3  ex:PublishFixedHeader_1764845868422    2

### CQ1.11u - Are RETAIN/DUP flags set in PUBLISH?

In [15]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?packet ?retain ?dup WHERE {
  ?packet a mqtt:PublishPacket ;
          mqtt:hasPublishFixedHeader ?header .
  OPTIONAL { ?header mqtt:hasRetainFlag ?retain }
  OPTIONAL { ?header mqtt:hasDUPFlag ?dup }
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

                           packet  retain    dup
0  ex:PublishPacket_1764845861738    True  False
1  ex:PublishPacket_1764845868422    True  False

### CQ1.12u - Which MQTT Control Packets have which PacketIdentifier?

In [16]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?packet  ?type ?id WHERE {
  ?packet a mqtt:ControlPacket ;
          a ?type ;
          mqtt:hasVariableHeader ?variable .
  ?variable mqtt:hasPacketIdentifier ?id .

  ?type rdfs:subClassOf* mqtt:ControlPacket .

  FILTER( STRSTARTS(STR(?type), STR(mqtt:)) )
  FILTER( ?type != mqtt:ControlPacket )
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

Empty DataFrame
Columns: [packet, type, id]
Index: []

### CQ1.13u - Which MQTT SUBSCRIBE payloads contain which SubscriptionEntries?

In [17]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?payload ?entry WHERE {
  ?payload a mqtt:SubscribePayload ;
           mqtt:hasSubscriptions ?entry .
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

                             payload                          entry
0  ex:SubscribePayload_1764800258251  ex:SubscriptionEntry_actuator

### CQ1.14u - Which MQTT Topic Filters (with QoS) are requested by a SubscriptionEntry?

In [18]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?entry ?filter ?qos WHERE {
  ?entry a mqtt:SubscriptionEntry ;
    OPTIONAL { ?entry mqtt:hasTopicFilter ?filter }  
    OPTIONAL { ?entry mqtt:hasQoSLevel ?qos }
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

                                 entry             filter  qos
0        ex:SubscriptionEntry_actuator  ex:Topic_actuator  NaN
1  ex:PublishFixedHeader_1764845861738                NaN  2.0
2  ex:PublishFixedHeader_1764845868422                NaN  2.0

### CQ1.15u - Which MQTT UNSUBSCRIBE payloads remove which MQTT TopicFilters?

In [19]:
q = """

PREFIX mqtt: <https://doernern.github.io/MQTT4SSNOntology/MQTT4SSN.owl#>

SELECT ?payload ?filter WHERE {
  ?payload a mqtt:UnsubscribePayload ;
           mqtt:hasTopicFilter ?filter .
}

"""

df = sparql_dataframe.get(endpoint, q)
df_short = strip_namespaces(df)
df_short

                               payload             filter
0  ex:UnsubscribePayload_1764800251677  ex:Topic_actuator